/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WowXYZERC20 } from "./WowXYZERC20.js";
export * as factories from "./factories/index.js";
export { WowXYZERC20__factory } from "./factories/WowXYZERC20__factory.js";
